/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import method.method_karyawan;
/**
 *
 * @author Muhammad Rydwan
 */
public class form_karyawan extends javax.swing.JFrame {

    /**
     * Creates new form form_karyawan
     */
    public form_karyawan() {
        initComponents();
       
        setExtendedState(MAXIMIZED_BOTH);
        new method_karyawan().kunci(this);
        new method_karyawan().bersih(this);
        new method_karyawan().tampil_data(this);
        new method_karyawan().kd_oto(this);
        
        jtID.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtAlamat = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jtTelepon = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jtUsername = new javax.swing.JTextField();
        jpPassword = new javax.swing.JPasswordField();
        jpKonfirmasi = new javax.swing.JPasswordField();
        jLabel9 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblKaryawan = new javax.swing.JTable();
        jcStatus = new javax.swing.JComboBox<>();
        jtID = new javax.swing.JTextField();
        btnTambah1 = new javax.swing.JButton();
        jcCari = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jtCari = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jtNama = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1252, 544));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Cari : ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 190, -1, -1));

        jtAlamat.setColumns(20);
        jtAlamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtAlamat.setRows(5);
        jScrollPane1.setViewportView(jtAlamat);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 220, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Alamat");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("No. Telepon");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, -1, -1));

        jtTelepon.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtTelepon.setText("jTextField1");
        getContentPane().add(jtTelepon, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 410, 220, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Status");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, -1, -1));

        jtUsername.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtUsername.setText("jTextField4");
        getContentPane().add(jtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 490, 220, -1));

        jpPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpPassword.setText("jPasswordField1");
        getContentPane().add(jpPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, 220, -1));

        jpKonfirmasi.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jpKonfirmasi.setText("jPasswordField2");
        getContentPane().add(jpKonfirmasi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 560, 220, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Username");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, -1));

        btnKembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 0, 0));
        btnKembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back(1).png"))); // NOI18N
        btnKembali.setText("Kembali");
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });
        getContentPane().add(btnKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 650, 130, 50));

        tblKaryawan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKaryawan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKaryawanMouseClicked(evt);
            }
        });
        tblKaryawan.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                tblKaryawanPropertyChange(evt);
            }
        });
        jScrollPane2.setViewportView(tblKaryawan);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 740, 390));

        jcStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jcStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilihan--", "admin", "pegawai" }));
        getContentPane().add(jcStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 440, 144, -1));

        jtID.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtID.setText("jTextField1");
        getContentPane().add(jtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 230, 172, -1));

        btnTambah1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTambah1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tambah32.png"))); // NOI18N
        btnTambah1.setText("Tambah");
        btnTambah1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambah1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnTambah1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, 40));

        jcCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jcCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nama", "Alamat", "Status", "Username" }));
        jcCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcCariActionPerformed(evt);
            }
        });
        getContentPane().add(jcCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 110, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Nama");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, -1));

        jtCari.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtCariActionPerformed(evt);
            }
        });
        getContentPane().add(jtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 190, 220, -1));

        jPanel5.setBackground(new java.awt.Color(255, 80, 125));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/team(1).png"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Karyawan");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 150));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSimpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/add user 32px.png"))); // NOI18N
        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        jPanel4.add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, 120, 60));

        btnUbah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit user 32px.png"))); // NOI18N
        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });
        jPanel4.add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 120, 60));

        btnHapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 0, 0));
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user32.png"))); // NOI18N
        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        jPanel4.add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 500, 120, 60));

        btnTambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/reload 32.png"))); // NOI18N
        btnTambah.setText("Batal");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });
        jPanel4.add(btnTambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 110, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("ID Karyawan");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));

        jtNama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtNama.setText("jTextField1");
        jPanel4.add(jtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 220, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Konfirmasi Password");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 440, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Password");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, 120, 560, 600));

        jPanel7.setBackground(new java.awt.Color(255, 80, 125));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 720, 1420, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblKaryawanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKaryawanMouseClicked
      new method_karyawan().klik_table(this);
    }//GEN-LAST:event_tblKaryawanMouseClicked

    private void tblKaryawanPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_tblKaryawanPropertyChange
        // TODO add your handling code here:
     
    }//GEN-LAST:event_tblKaryawanPropertyChange

    private void btnTambah1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambah1ActionPerformed
         new method_karyawan().buka_kunci(this);
         new method_karyawan().bersih(this);
          new method_karyawan().kd_oto(this);
    }//GEN-LAST:event_btnTambah1ActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
       new method_karyawan().simpan(this);
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
    new method_karyawan().ubah(this);
    }//GEN-LAST:event_btnUbahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        new method_karyawan().hapus(this);
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
       new method_karyawan().bersih(this);
        new method_karyawan().kunci(this);
        new method_karyawan().kd_oto(this);
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void jtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtCariActionPerformed
        // TODO add your handling code here:
        new method_karyawan().cari_data(this);
    }//GEN-LAST:event_jtCariActionPerformed

    private void jcCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcCariActionPerformed
       jtCari.requestFocus();
    }//GEN-LAST:event_jcCariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_karyawan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_karyawan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnHapus;
    public javax.swing.JButton btnKembali;
    public javax.swing.JButton btnSimpan;
    public javax.swing.JButton btnTambah;
    public javax.swing.JButton btnTambah1;
    public javax.swing.JButton btnUbah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JComboBox<String> jcCari;
    public javax.swing.JComboBox<String> jcStatus;
    public javax.swing.JPasswordField jpKonfirmasi;
    public javax.swing.JPasswordField jpPassword;
    public javax.swing.JTextArea jtAlamat;
    public javax.swing.JTextField jtCari;
    public javax.swing.JTextField jtID;
    public javax.swing.JTextField jtNama;
    public javax.swing.JTextField jtTelepon;
    public javax.swing.JTextField jtUsername;
    public javax.swing.JTable tblKaryawan;
    // End of variables declaration//GEN-END:variables
}
