/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

/**
 *
 * @author Muhammad Rydwan
 */
public class form_pelanggan extends javax.swing.JFrame {

    /**
     * Creates new form pelanggan
     */
    public form_pelanggan() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        jtidpelanggan.setEnabled(false);
        new method.method_pelanggan().bersih(this);
        new method.method_pelanggan().kunci(this);
        new method.method_pelanggan().id_oto(this);
        new method.method_pelanggan().tampil_data(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jbsimpan = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jccari = new javax.swing.JComboBox<>();
        jtcari = new javax.swing.JTextField();
        jbkembali = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jtidpelanggan = new javax.swing.JTextField();
        jbtambah = new javax.swing.JButton();
        jbbatal = new javax.swing.JButton();
        jtnama = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtalamat = new javax.swing.JTextArea();
        jtno = new javax.swing.JTextField();
        jbubah = new javax.swing.JButton();
        jbhapus = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("ID Pelanggan ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Nama");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Alamat");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("No. Telepon");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 230, 800, 400));

        jbsimpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/add user 32px.png"))); // NOI18N
        jbsimpan.setText("Simpan");
        jbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jbsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, 120, 50));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Cari :");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 200, -1, -1));

        jccari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nama", "Alamat", "Telepon" }));
        getContentPane().add(jccari, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 200, 120, -1));

        jtcari.setText("jTextField5");
        jtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcariActionPerformed(evt);
            }
        });
        getContentPane().add(jtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 200, 280, -1));

        jbkembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbkembali.setForeground(new java.awt.Color(255, 0, 0));
        jbkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back(1).png"))); // NOI18N
        jbkembali.setText("Kembali");
        jbkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jbkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 650, 130, 60));

        jPanel5.setBackground(new java.awt.Color(255, 189, 68));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pelanggan 128px.png"))); // NOI18N
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel10.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Data Pelanggan");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 150));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtidpelanggan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtidpelanggan.setText("jTextField1");
        jtidpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtidpelangganActionPerformed(evt);
            }
        });
        jPanel7.add(jtidpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 146, 25));

        jbtambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tambah32.png"))); // NOI18N
        jbtambah.setText("Tambah");
        jbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtambahActionPerformed(evt);
            }
        });
        jPanel7.add(jbtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 120, 40));

        jbbatal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/reload 32.png"))); // NOI18N
        jbbatal.setText("Batal");
        jbbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbatalActionPerformed(evt);
            }
        });
        jPanel7.add(jbbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 60, 110, 40));

        jtnama.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtnama.setText("jTextField2");
        jPanel7.add(jtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, 304, 27));

        jtalamat.setColumns(20);
        jtalamat.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtalamat.setRows(5);
        jScrollPane2.setViewportView(jtalamat);

        jPanel7.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 290, -1));

        jtno.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtno.setText("jTextField4");
        jPanel7.add(jtno, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 222, 29));

        jbubah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edit user 32px.png"))); // NOI18N
        jbubah.setText("Ubah");
        jbubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbubahActionPerformed(evt);
            }
        });
        jPanel7.add(jbubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 110, 50));

        jbhapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbhapus.setForeground(new java.awt.Color(255, 0, 0));
        jbhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/user32.png"))); // NOI18N
        jbhapus.setText("Hapus");
        jbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhapusActionPerformed(evt);
            }
        });
        jPanel7.add(jbhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 390, 120, 50));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 520, 570));

        jPanel8.setBackground(new java.awt.Color(255, 189, 68));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 720, 1420, 100));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsimpanActionPerformed
       new method.method_pelanggan().simpan(this);
    }//GEN-LAST:event_jbsimpanActionPerformed

    private void jbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtambahActionPerformed
        // TODO add your handling code here:
        new method.method_pelanggan().buka_kunci(this);
    }//GEN-LAST:event_jbtambahActionPerformed

    private void jtidpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtidpelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtidpelangganActionPerformed

    private void jbkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbkembaliActionPerformed
        dispose();
       
    }//GEN-LAST:event_jbkembaliActionPerformed

    private void jbbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbatalActionPerformed
        new method.method_pelanggan().bersih(this);
        new method.method_pelanggan().kunci(this);
        new method.method_pelanggan().id_oto(this);
    }//GEN-LAST:event_jbbatalActionPerformed

    private void jbubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbubahActionPerformed
        new method.method_pelanggan().ubah(this);
    }//GEN-LAST:event_jbubahActionPerformed

    private void jbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhapusActionPerformed
       new method.method_pelanggan().hapus(this);
    }//GEN-LAST:event_jbhapusActionPerformed

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
      new method.method_pelanggan().klik_table(this);
    }//GEN-LAST:event_jtableMouseClicked

    private void jtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcariActionPerformed
        new method.method_pelanggan().cari_data(this);
    }//GEN-LAST:event_jtcariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pelanggan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    public javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jbbatal;
    public javax.swing.JButton jbhapus;
    public javax.swing.JButton jbkembali;
    public javax.swing.JButton jbsimpan;
    public javax.swing.JButton jbtambah;
    public javax.swing.JButton jbubah;
    public javax.swing.JComboBox<String> jccari;
    public javax.swing.JTable jtable;
    public javax.swing.JTextArea jtalamat;
    public javax.swing.JTextField jtcari;
    public javax.swing.JTextField jtidpelanggan;
    public javax.swing.JTextField jtnama;
    public javax.swing.JTextField jtno;
    // End of variables declaration//GEN-END:variables
}
