/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import javax.swing.JOptionPane;
import java.sql.Statement;
import java.sql.Connection;
import java.sql.ResultSet;

/**
 *
 * @author Muhammad Rydwan
 */
public class form_menu_utama extends javax.swing.JFrame {
        Connection con = new rental_mobil.Rental_mobil().getCon();
        Statement stat = null;
        ResultSet res = null;
        String sql = "";
    /**
     * Creates new form form_menu_utama
     * @param idkaryawan
     */
    public form_menu_utama(String idkaryawan) {
        initComponents();
        
        lbidkaryawan.setText(idkaryawan);
            
        try {
            sql = "SELECT * FROM karyawan WHERE id_karyawan = '"+lbidkaryawan.getText()+"' ";
            stat = con.createStatement();
            res = stat.executeQuery(sql);
            
            while(res.next()){
                
                if(res.getString(5).equals("admin")){
                    btnKaryawan.setEnabled(true);
                    btnMobil.setEnabled(true);
                    btnPelanggan.setEnabled(true);
                    btnMerental.setEnabled(true);
                    btnTransaksi.setEnabled(true);
                    lbStatus.setText(res.getString(5));
                }else if(res.getString(5).equals("pegawai")){
                    btnKaryawan.setEnabled(false);
                    btnMobil.setEnabled(true);
                    btnPelanggan.setEnabled(true);
                    btnMerental.setEnabled(true);
                    btnTransaksi.setEnabled(true);
                    lbStatus.setText(res.getString(5));
                }
                    
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
        setExtendedState(MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbidkaryawan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbStatus = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnMerental = new javax.swing.JButton();
        btnLaporan = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnKaryawan = new javax.swing.JButton();
        btnMobil = new javax.swing.JButton();
        btnPelanggan = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(240, 240, 240));
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setToolTipText("");
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbidkaryawan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbidkaryawan.setText("[id_karyawan]");
        lbidkaryawan.setToolTipText("");
        jPanel1.add(lbidkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID Karyawan :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Login Sebagai : ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 20, -1, -1));

        lbStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lbStatus.setText("[status]");
        jPanel1.add(lbStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 710, 1590, 70));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Proses", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnMerental.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMerental.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/rent-a-car128.png"))); // NOI18N
        btnMerental.setText("Merental");
        btnMerental.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMerental.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMerental.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMerental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMerentalActionPerformed(evt);
            }
        });
        jPanel4.add(btnMerental, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 182, 164));

        btnLaporan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/reprt128.png"))); // NOI18N
        btnLaporan.setText("Cetak Laporan");
        btnLaporan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnLaporan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnLaporan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaporanActionPerformed(evt);
            }
        });
        jPanel4.add(btnLaporan, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 30, 182, 164));

        btnTransaksi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transaction128.png"))); // NOI18N
        btnTransaksi.setText("Transaksi");
        btnTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransaksi.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnTransaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        jPanel4.add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 182, 164));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 640, 220));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Data Master", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnKaryawan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/team(1).png"))); // NOI18N
        btnKaryawan.setText("Data Karyawan");
        btnKaryawan.setAlignmentY(11.0F);
        btnKaryawan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKaryawan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnKaryawan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawanActionPerformed(evt);
            }
        });
        jPanel2.add(btnKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 182, 164));

        btnMobil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/carbtn_128.png"))); // NOI18N
        btnMobil.setText("Data Mobil");
        btnMobil.setToolTipText("");
        btnMobil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMobil.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMobil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMobilActionPerformed(evt);
            }
        });
        jPanel2.add(btnMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 182, 164));

        btnPelanggan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pelanggan 128px.png"))); // NOI18N
        btnPelanggan.setText("Data Pelanggan");
        btnPelanggan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPelanggan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPelanggan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });
        jPanel2.add(btnPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 30, 182, 164));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 620, 220));

        jPanel5.setBackground(new java.awt.Color(63, 101, 243));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aplikasi Rental Mobil");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 100));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 3, true));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/exit 32px.png"))); // NOI18N
        jButton1.setText("Logout");
        jButton1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 30, 140, 40));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 1060, 100));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/car_256.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/car2_256px.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanActionPerformed
        new form.form_karyawan().setVisible(true);
    }//GEN-LAST:event_btnKaryawanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       int pesan =  JOptionPane.showConfirmDialog(null, "Apakah Anda yakin untuk Logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
       if(pesan == JOptionPane.YES_OPTION){
           this.dispose();
           new form.form_login().setVisible(true);
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMobilActionPerformed
        new form.form_mobil().setVisible(true);
       
    }//GEN-LAST:event_btnMobilActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
      new form.form_pelanggan().setVisible(true);
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnMerentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMerentalActionPerformed
       String idkaryawan = lbidkaryawan.getText();
       form_merental form = new form_merental(idkaryawan);
       form.setVisible(true);
         
    }//GEN-LAST:event_btnMerentalActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
        new form.form_transaksi().setVisible(true);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    private void btnLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaporanActionPerformed
       new form.form_laporan().setVisible(true);
    }//GEN-LAST:event_btnLaporanActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnKaryawan;
    public javax.swing.JButton btnLaporan;
    public javax.swing.JButton btnMerental;
    public javax.swing.JButton btnMobil;
    public javax.swing.JButton btnPelanggan;
    public javax.swing.JButton btnTransaksi;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JLabel lbStatus;
    public javax.swing.JLabel lbidkaryawan;
    // End of variables declaration//GEN-END:variables
}
