/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package form;


/**
 *
 * @author Muhammad Rydwan
 */
public class form_mobil extends javax.swing.JFrame {

    /** Creates new form form_mobil */
    public form_mobil() {
        initComponents();
        new method.method_mobil().kunci(this);
        new method.method_mobil().bersih(this);
        new method.method_mobil().tampil_data(this);
        new method.method_mobil().kd_oto(this);
       
        
        setExtendedState(MAXIMIZED_BOTH);
        jtid.setEnabled(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel12 = new javax.swing.JLabel();
        jtid = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtablemobil = new javax.swing.JTable();
        jbtambah = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jccari = new javax.swing.JComboBox<>();
        jtcari = new javax.swing.JTextField();
        jbkembali = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jtnama = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jbbatal = new javax.swing.JButton();
        jbsimpan = new javax.swing.JButton();
        jbubah = new javax.swing.JButton();
        jbhapus = new javax.swing.JButton();
        jtharga = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jtwarna = new javax.swing.JTextField();
        jtpolisi = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("ID Mobil");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        jtid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtid.setText("jTextField1");
        getContentPane().add(jtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 230, 150, -1));

        jtablemobil.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtablemobil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtablemobilMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtablemobil);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 830, 360));

        jbtambah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbtambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tambah32.png"))); // NOI18N
        jbtambah.setText("Tambah");
        jbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtambahActionPerformed(evt);
            }
        });
        getContentPane().add(jbtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 181, 120, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Cari : ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, -1, -1));

        jccari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jccari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "Nama", "Harga", "Warna", "No. Polisi" }));
        jccari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jccariActionPerformed(evt);
            }
        });
        getContentPane().add(jccari, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 137, -1));

        jtcari.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jtcari.setText("jTextField6");
        jtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcariActionPerformed(evt);
            }
        });
        getContentPane().add(jtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 200, -1));

        jbkembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbkembali.setForeground(new java.awt.Color(255, 0, 0));
        jbkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back(1).png"))); // NOI18N
        jbkembali.setText("Kembali");
        jbkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jbkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 610, 120, 60));

        jPanel5.setBackground(new java.awt.Color(0, 148, 251));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/carbtn_128.png"))); // NOI18N
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Data Mobil");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 150));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtnama.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtnama.setText("jTextField2");
        jPanel6.add(jtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 297, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Nama Mobil");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        jbbatal.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/reload 32.png"))); // NOI18N
        jbbatal.setText("Batal");
        jbbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbatalActionPerformed(evt);
            }
        });
        jPanel6.add(jbbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 31, 100, 40));

        jbsimpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/floppy-disk 32.png"))); // NOI18N
        jbsimpan.setText("Simpan ");
        jbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsimpanActionPerformed(evt);
            }
        });
        jPanel6.add(jbsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, 58));

        jbubah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edt32.png"))); // NOI18N
        jbubah.setText("Ubah");
        jbubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbubahActionPerformed(evt);
            }
        });
        jPanel6.add(jbubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 110, 58));

        jbhapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbhapus.setForeground(new java.awt.Color(255, 0, 0));
        jbhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/batal32.png"))); // NOI18N
        jbhapus.setText("Hapus");
        jbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhapusActionPerformed(evt);
            }
        });
        jPanel6.add(jbhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 420, 110, 58));

        jtharga.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtharga.setText("jTextField2");
        jPanel6.add(jtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 190, -1));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Rp.");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Harga Sewa");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Warna");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, -1));

        jtwarna.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtwarna.setText("jTextField2");
        jPanel6.add(jtwarna, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 194, -1));

        jtpolisi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jtpolisi.setText("jTextField2");
        jPanel6.add(jtpolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 141, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("No. Polisi");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 500, 540));

        jPanel7.setBackground(new java.awt.Color(0, 148, 251));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 690, 1390, 90));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbubahActionPerformed
       new method.method_mobil().ubah(this);
    }//GEN-LAST:event_jbubahActionPerformed

    private void jbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsimpanActionPerformed
        // TODO add your handling code here:
        new method.method_mobil().simpan(this);
    }//GEN-LAST:event_jbsimpanActionPerformed

    private void jbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhapusActionPerformed
        // TODO add your handling code here:
        new method.method_mobil().hapus(this);
    }//GEN-LAST:event_jbhapusActionPerformed

    private void jbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtambahActionPerformed
        // TODO add your handling code here:
           new method.method_mobil().buka_kunci(this);
           new method.method_mobil().bersih(this);
           new method.method_mobil().kd_oto(this);
    }//GEN-LAST:event_jbtambahActionPerformed

    private void jbkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbkembaliActionPerformed
      this.dispose();
    }//GEN-LAST:event_jbkembaliActionPerformed

    private void jtablemobilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtablemobilMouseClicked
        new method.method_mobil().klik_table(this);
    }//GEN-LAST:event_jtablemobilMouseClicked

    private void jtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcariActionPerformed
        // TODO add your handling code here:
         new method.method_mobil().cari_data(this);
    }//GEN-LAST:event_jtcariActionPerformed

    private void jbbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbatalActionPerformed
       new method.method_mobil().bersih(this);
       new method.method_mobil().kunci(this);
       
    }//GEN-LAST:event_jbbatalActionPerformed

    private void jccariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jccariActionPerformed
       jtcari.requestFocus();
    }//GEN-LAST:event_jccariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_mobil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_mobil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel12;
    public javax.swing.JLabel jLabel13;
    public javax.swing.JLabel jLabel14;
    public javax.swing.JLabel jLabel15;
    public javax.swing.JLabel jLabel16;
    public javax.swing.JLabel jLabel17;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbbatal;
    public javax.swing.JButton jbhapus;
    public javax.swing.JButton jbkembali;
    public javax.swing.JButton jbsimpan;
    public javax.swing.JButton jbtambah;
    public javax.swing.JButton jbubah;
    public javax.swing.JComboBox<String> jccari;
    public javax.swing.JTable jtablemobil;
    public javax.swing.JTextField jtcari;
    public javax.swing.JTextField jtharga;
    public javax.swing.JTextField jtid;
    public javax.swing.JTextField jtnama;
    public javax.swing.JTextField jtpolisi;
    public javax.swing.JTextField jtwarna;
    // End of variables declaration//GEN-END:variables

}
