/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;


/**
 *
 * @author Muhammad Rydwan
 */
public class form_transaksi extends javax.swing.JFrame {

    /**
     * Creates new form form_transaksi
     */
    public form_transaksi() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        new method.method_transaksi().bersih(this);
        new method.method_transaksi().kunci(this);
        
        new method.method_transaksi().id_oto(this);
        new method.method_transaksi().tampil_data(this);
        new method.method_transaksi().tampil_no_rental(this);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jtidtransaksi = new javax.swing.JTextField();
        jbubah = new javax.swing.JButton();
        jbtambah = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();
        jbhapus = new javax.swing.JButton();
        jbkembali = new javax.swing.JButton();
        jbsimpan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jccari = new javax.swing.JComboBox<>();
        jtcari = new javax.swing.JTextField();
        jbbatal = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jtnorental = new javax.swing.JTextField();
        jcnorental = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jtnamapelanggan = new javax.swing.JTextField();
        jtnamamobil = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jttanggalrental = new javax.swing.JTextField();
        jthargasewa = new javax.swing.JTextField();
        jttanggalkembali = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jtidpelanggan = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jtidmobil = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtpotongan = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jtharga = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jttotalharga = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jtdibayar = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbstatus = new javax.swing.JLabel();
        jtkembalian = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jtlamasewa = new javax.swing.JTextField();
        jtidkaryawan = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel29 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("ID Transaksi");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jtidtransaksi.setText("jTextField1");
        getContentPane().add(jtidtransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 120, 161, 30));

        jbubah.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbubah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/edt32.png"))); // NOI18N
        jbubah.setText("Ubah");
        jbubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbubahActionPerformed(evt);
            }
        });
        getContentPane().add(jbubah, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 490, -1, 53));

        jbtambah.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbtambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/tambah32.png"))); // NOI18N
        jbtambah.setText("Tambah");
        jbtambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtambahActionPerformed(evt);
            }
        });
        getContentPane().add(jbtambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 70, -1, 40));

        jtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 860, 300));

        jbhapus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbhapus.setForeground(new java.awt.Color(255, 0, 0));
        jbhapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/batal32.png"))); // NOI18N
        jbhapus.setText("Hapus");
        jbhapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbhapusActionPerformed(evt);
            }
        });
        getContentPane().add(jbhapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 490, 110, 53));

        jbkembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbkembali.setForeground(new java.awt.Color(255, 0, 0));
        jbkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back(1).png"))); // NOI18N
        jbkembali.setText("Kembali");
        jbkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jbkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1220, 700, 130, 53));

        jbsimpan.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbsimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/checked32.png"))); // NOI18N
        jbsimpan.setText("Proses");
        jbsimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbsimpanActionPerformed(evt);
            }
        });
        getContentPane().add(jbsimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 490, -1, 53));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Cari :");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 102, -1, -1));

        jccari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Transaksi", "No Rental", "Harga", "Potongan", "Total Harga", "Dibayar", "Kembalian", "Status", "ID Karyawan" }));
        jccari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jccariActionPerformed(evt);
            }
        });
        getContentPane().add(jccari, new org.netbeans.lib.awtextra.AbsoluteConstraints(556, 100, 130, 33));

        jtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtcariActionPerformed(evt);
            }
        });
        getContentPane().add(jtcari, new org.netbeans.lib.awtextra.AbsoluteConstraints(696, 99, 230, 34));

        jbbatal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jbbatal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/batal32.png"))); // NOI18N
        jbbatal.setText("Batal");
        jbbatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbbatalActionPerformed(evt);
            }
        });
        getContentPane().add(jbbatal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 100, 40));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("No Rental");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 14, -1, -1));

        jtnorental.setText("jTextField2");
        jPanel2.add(jtnorental, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 13, 161, 30));

        jcnorental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilihan--" }));
        jcnorental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcnorentalActionPerformed(evt);
            }
        });
        jPanel2.add(jcnorental, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 53, 161, 32));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Nama Pelanggan");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 145, -1, -1));

        jtnamapelanggan.setEditable(false);
        jtnamapelanggan.setText("jTextField1");
        jPanel2.add(jtnamapelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 145, 214, 30));

        jtnamamobil.setEditable(false);
        jtnamamobil.setText("jTextField1");
        jPanel2.add(jtnamamobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 232, 214, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel17.setText("Nama Mobil");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 232, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Harga Sewa");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 287, -1, -1));

        jttanggalrental.setEditable(false);
        jttanggalrental.setText("jTextField1");
        jPanel2.add(jttanggalrental, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 337, 159, 30));

        jthargasewa.setEditable(false);
        jthargasewa.setText("jTextField1");
        jPanel2.add(jthargasewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 286, 172, 30));

        jttanggalkembali.setEditable(false);
        jttanggalkembali.setText("jTextField1");
        jPanel2.add(jttanggalkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 378, 159, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel18.setText("Tanggal Kembali");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 379, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Tanggal Rental");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 338, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel25.setText("ID Pelanggan");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 104, -1, -1));

        jtidpelanggan.setEditable(false);
        jtidpelanggan.setText("jTextField1");
        jtidpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtidpelangganActionPerformed(evt);
            }
        });
        jPanel2.add(jtidpelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 103, 214, 30));

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel26.setText("ID Mobil");
        jPanel2.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 196, -1, -1));

        jtidmobil.setEditable(false);
        jtidmobil.setText("jTextField1");
        jtidmobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtidmobilActionPerformed(evt);
            }
        });
        jPanel2.add(jtidmobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 195, 214, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 440, 420));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 0));
        jLabel5.setText("Harga");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 25, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 0, 0));
        jLabel6.setText("Potongan");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 73, -1, -1));

        jtpotongan.setText("jTextField4");
        jtpotongan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtpotonganKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtpotonganKeyTyped(evt);
            }
        });
        jPanel1.add(jtpotongan, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 73, 204, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Rp.");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 26, -1, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Rp.");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 74, -1, -1));

        jtharga.setEditable(false);
        jtharga.setText("jTextField4");
        jPanel1.add(jtharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 25, 204, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 630, 440, 120));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 0));
        jLabel3.setText("Total Harga");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 16, -1, -1));

        jttotalharga.setEditable(false);
        jttotalharga.setText("jTextField5");
        jPanel3.add(jttotalharga, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 15, 202, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Rp.");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 16, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel16.setText("Dibayar");
        jLabel16.setToolTipText("");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 63, -1, -1));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setText("Rp.");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 64, -1, -1));

        jtdibayar.setText("jTextField5");
        jtdibayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtdibayarKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtdibayarKeyTyped(evt);
            }
        });
        jPanel3.add(jtdibayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 63, 202, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 255, 51));
        jLabel22.setText("Kembalian");
        jLabel22.setToolTipText("");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 99, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel23.setText("Rp.");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 100, -1, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 255));
        jLabel24.setText("Status");
        jLabel24.setToolTipText("");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 156, -1, -1));

        lbstatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lbstatus.setForeground(new java.awt.Color(255, 0, 0));
        lbstatus.setText("[LUNAS/BELUM LUNAS]");
        lbstatus.setToolTipText("");
        jPanel3.add(lbstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 156, -1, -1));

        jtkembalian.setEditable(false);
        jtkembalian.setText("jTextField5");
        jPanel3.add(jtkembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 99, 202, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 400, 230));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel20.setText("Lama Sewa (Hari)");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 590, -1, -1));

        jtlamasewa.setText("jTextField1");
        jtlamasewa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtlamasewaActionPerformed(evt);
            }
        });
        jtlamasewa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtlamasewaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtlamasewaKeyTyped(evt);
            }
        });
        getContentPane().add(jtlamasewa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 590, 110, 30));

        jtidkaryawan.setEditable(false);
        jtidkaryawan.setText("jTextField1");
        getContentPane().add(jtidkaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 720, 159, 30));

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel27.setText("ID Karyawan");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 720, -1, -1));

        jPanel5.setBackground(new java.awt.Color(255, 130, 121));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel29.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Transaksi");
        jPanel5.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1390, 60));

        jLabel28.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transaction128.png"))); // NOI18N
        getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 580, -1, -1));

        jPanel10.setBackground(new java.awt.Color(255, 130, 121));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 760, 1420, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jccariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jccariActionPerformed
       jtcari.requestFocus();
    }//GEN-LAST:event_jccariActionPerformed

    private void jbtambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtambahActionPerformed
       new method.method_transaksi().buka_kunci(this);
       new method.method_transaksi().validasi_no_rental(this);
    }//GEN-LAST:event_jbtambahActionPerformed

    private void jbkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbkembaliActionPerformed
        dispose();
    }//GEN-LAST:event_jbkembaliActionPerformed

    private void jbbatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbbatalActionPerformed
        new method.method_transaksi().kunci(this);
        new method.method_transaksi().bersih_batal(this);
    }//GEN-LAST:event_jbbatalActionPerformed

    private void jtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableMouseClicked
        new method.method_transaksi().klik_table(this);
    }//GEN-LAST:event_jtableMouseClicked

    private void jtidpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtidpelangganActionPerformed
       
    }//GEN-LAST:event_jtidpelangganActionPerformed

    private void jcnorentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcnorentalActionPerformed
    new method.method_transaksi().tampil_detail_merental(this);
    new method.method_transaksi().tampil_nama_mobil(this);
    new method.method_transaksi().tampil_nama_pelanggan(this);
    new method.method_transaksi().validasi_no_rental(this);
    jtlamasewa.requestFocus();
    }//GEN-LAST:event_jcnorentalActionPerformed

    private void jtidmobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtidmobilActionPerformed
        
    }//GEN-LAST:event_jtidmobilActionPerformed

    private void jtlamasewaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtlamasewaKeyTyped
       char karakter = evt.getKeyChar();
       if(!(((karakter >= '0')&&(karakter <= '9') || (karakter  == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) ) )){
           //getToolkit().beep();
           evt.consume();
       }
    }//GEN-LAST:event_jtlamasewaKeyTyped

    private void jtlamasewaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtlamasewaKeyPressed
        try {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            int harga_sewa = Integer.parseInt(jthargasewa.getText());
            int lamasewa = Integer.parseInt(jtlamasewa.getText());
        
            int harga = harga_sewa * lamasewa;
        
        jtharga.setText(Integer.toString(harga));
        jtpotongan.requestFocus();
        
        }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Tolong Isi Field!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtlamasewaKeyPressed

    private void jtpotonganKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpotonganKeyTyped
       char karakter = evt.getKeyChar();
       if(!(((karakter >= '0')&&(karakter <= '9') || (karakter  == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE) ) )){
           //getToolkit().beep();
           evt.consume();
       }
    }//GEN-LAST:event_jtpotonganKeyTyped

    private void jtpotonganKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtpotonganKeyPressed
       try {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
            int harga = Integer.parseInt(jtharga.getText());
            int potongan = Integer.parseInt(jtpotongan.getText());
        
            int totalharga = harga - potongan;
        
        jttotalharga.setText(Integer.toString(totalharga));
        jtdibayar.requestFocus();
        
        }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(null, "Tolong Isi Field!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtpotonganKeyPressed

    private void jtdibayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtdibayarKeyTyped
       char karakter = evt.getKeyChar();
       if(!(((karakter >= '0')&&(karakter <='9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
           //getToolkit().beep();
           evt.consume();
       }
    }//GEN-LAST:event_jtdibayarKeyTyped

    private void jtdibayarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtdibayarKeyPressed
        try {
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
                int totalharga = Integer.parseInt(jttotalharga.getText());
                int dibayar = Integer.parseInt(jtdibayar.getText());
                
                int kembalian = dibayar - totalharga;
                jtkembalian.setText(Integer.toString(kembalian));
                
                if(dibayar == totalharga){
                    lbstatus.setText("LUNAS");
                }else if(dibayar < totalharga){
                    lbstatus.setText("BELUM LUNAS");
                    jtkembalian.setText("0");
                }else if(dibayar > totalharga){
                    lbstatus.setText("LUNAS");
                }
                jbsimpan.doClick();
                
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Tolong Isi Field!", "Peringatan", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jtdibayarKeyPressed

    private void jbsimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbsimpanActionPerformed
       new method.method_transaksi().simpan(this);
    }//GEN-LAST:event_jbsimpanActionPerformed

    private void jbhapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbhapusActionPerformed
       new method.method_transaksi().hapus(this);
    }//GEN-LAST:event_jbhapusActionPerformed

    private void jbubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbubahActionPerformed
       new method.method_transaksi().ubah(this);
    }//GEN-LAST:event_jbubahActionPerformed

    private void jtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtcariActionPerformed
        new method.method_transaksi().cari_data(this);
    }//GEN-LAST:event_jtcariActionPerformed

    private void jtlamasewaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtlamasewaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtlamasewaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbbatal;
    public javax.swing.JButton jbhapus;
    public javax.swing.JButton jbkembali;
    public javax.swing.JButton jbsimpan;
    public javax.swing.JButton jbtambah;
    public javax.swing.JButton jbubah;
    public javax.swing.JComboBox<String> jccari;
    public javax.swing.JComboBox<String> jcnorental;
    public javax.swing.JTable jtable;
    public javax.swing.JTextField jtcari;
    public javax.swing.JTextField jtdibayar;
    public javax.swing.JTextField jtharga;
    public javax.swing.JTextField jthargasewa;
    public javax.swing.JTextField jtidkaryawan;
    public javax.swing.JTextField jtidmobil;
    public javax.swing.JTextField jtidpelanggan;
    public javax.swing.JTextField jtidtransaksi;
    public javax.swing.JTextField jtkembalian;
    public javax.swing.JTextField jtlamasewa;
    public javax.swing.JTextField jtnamamobil;
    public javax.swing.JTextField jtnamapelanggan;
    public javax.swing.JTextField jtnorental;
    public javax.swing.JTextField jtpotongan;
    public javax.swing.JTextField jttanggalkembali;
    public javax.swing.JTextField jttanggalrental;
    public javax.swing.JTextField jttotalharga;
    public javax.swing.JLabel lbstatus;
    // End of variables declaration//GEN-END:variables
}
