/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

/**
 *
 * @author Muhammad Rydwan
 */
public class form_laporan extends javax.swing.JFrame {

    /**
     * Creates new form form_laporan
     */
    public form_laporan() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jbkembali = new javax.swing.JButton();
        btnMobil = new javax.swing.JButton();
        btnKaryawan = new javax.swing.JButton();
        btnPelanggan = new javax.swing.JButton();
        btnTransaksi = new javax.swing.JButton();
        btnMerental = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBackground(new java.awt.Color(25, 161, 249));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 720, 1420, 100));

        jPanel5.setBackground(new java.awt.Color(25, 150, 252));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/reprt128.png"))); // NOI18N
        jPanel5.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cetak Laporan");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1420, 150));

        jbkembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbkembali.setForeground(new java.awt.Color(204, 0, 0));
        jbkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back(1).png"))); // NOI18N
        jbkembali.setText("Kembali");
        jbkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jbkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 640, 130, 62));

        btnMobil.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMobil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/carbtn_128.png"))); // NOI18N
        btnMobil.setText("Laporan Data Mobil");
        btnMobil.setToolTipText("");
        btnMobil.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMobil.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMobil.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMobil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMobilActionPerformed(evt);
            }
        });
        getContentPane().add(btnMobil, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 350, 240, 164));

        btnKaryawan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnKaryawan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/team(1).png"))); // NOI18N
        btnKaryawan.setText("Laporan Data Karyawan");
        btnKaryawan.setAlignmentY(11.0F);
        btnKaryawan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnKaryawan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnKaryawan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKaryawanActionPerformed(evt);
            }
        });
        getContentPane().add(btnKaryawan, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, 240, 164));

        btnPelanggan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPelanggan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/pelanggan 128px.png"))); // NOI18N
        btnPelanggan.setText("Laporan Data Pelanggan");
        btnPelanggan.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnPelanggan.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnPelanggan.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPelangganActionPerformed(evt);
            }
        });
        getContentPane().add(btnPelanggan, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, 240, 164));

        btnTransaksi.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/transaction128.png"))); // NOI18N
        btnTransaksi.setText("Laporan Transaksi");
        btnTransaksi.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnTransaksi.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnTransaksi.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransaksiActionPerformed(evt);
            }
        });
        getContentPane().add(btnTransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 530, 240, 164));

        btnMerental.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnMerental.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/rent-a-car128.png"))); // NOI18N
        btnMerental.setText("Laporan Merental");
        btnMerental.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnMerental.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnMerental.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnMerental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMerentalActionPerformed(evt);
            }
        });
        getContentPane().add(btnMerental, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 240, 164));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbkembaliActionPerformed
        dispose();
    }//GEN-LAST:event_jbkembaliActionPerformed

    private void btnKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKaryawanActionPerformed
      new laporan_form.form_laporan_karyawan().setVisible(true);
    }//GEN-LAST:event_btnKaryawanActionPerformed

    private void btnMobilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMobilActionPerformed
        new laporan_form.form_laporan_mobil().setVisible(true);

    }//GEN-LAST:event_btnMobilActionPerformed

    private void btnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPelangganActionPerformed
        new laporan_form.form_laporan_pelanggan().setVisible(true);
    }//GEN-LAST:event_btnPelangganActionPerformed

    private void btnMerentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMerentalActionPerformed
        new laporan_form.form_laporan_merental().setVisible(true);

    }//GEN-LAST:event_btnMerentalActionPerformed

    private void btnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransaksiActionPerformed
         new laporan_form.form_laporan_transaksi().setVisible(true);
    }//GEN-LAST:event_btnTransaksiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnKaryawan;
    public javax.swing.JButton btnMerental;
    public javax.swing.JButton btnMobil;
    public javax.swing.JButton btnPelanggan;
    public javax.swing.JButton btnTransaksi;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel9;
    public javax.swing.JButton jbkembali;
    // End of variables declaration//GEN-END:variables
}
