/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package laporan_form;

import javax.swing.JOptionPane;

/**
 *
 * @author Muhammad Rydwan
 */
public class form_laporan_transaksi_status extends javax.swing.JFrame {

    /**
     * Creates new form form_laporan_transaksi_status
     */
    public form_laporan_transaksi_status() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jbcetak = new javax.swing.JButton();
        jbkembali = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jcstatus = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 213, 230));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Status");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 70));

        jPanel6.setBackground(new java.awt.Color(153, 213, 230));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 620, 50));

        jbcetak.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbcetak.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/printdsss 32.png"))); // NOI18N
        jbcetak.setText("Cetak");
        jbcetak.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jbcetak.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jbcetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbcetakActionPerformed(evt);
            }
        });
        getContentPane().add(jbcetak, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 110, 40));

        jbkembali.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jbkembali.setForeground(new java.awt.Color(204, 0, 0));
        jbkembali.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/back(1).png"))); // NOI18N
        jbkembali.setText("Kembali");
        jbkembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbkembaliActionPerformed(evt);
            }
        });
        getContentPane().add(jbkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 130, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Pilih Status :");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, -1, -1));

        jcstatus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jcstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Pilihan--", "LUNAS", "BELUM LUNAS" }));
        getContentPane().add(jcstatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 260, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jbcetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbcetakActionPerformed
        // TODO add your handling code here:
        if(jcstatus.getSelectedItem().equals("--Pilihan--")){
            JOptionPane.showMessageDialog(null, "Silihkan Pilih Status Transaksi!");
        }else if(jcstatus.getSelectedItem().equals("LUNAS")){
            new laporan_method.method_laporan_transaksi_status().cetak_lunas(this);
        }else if(jcstatus.getSelectedItem().equals("BELUM LUNAS")){
            new laporan_method.method_laporan_transaksi_status().cetak_belum_lunas(this);
        }
            
    }//GEN-LAST:event_jbcetakActionPerformed

    private void jbkembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbkembaliActionPerformed
        dispose();
    }//GEN-LAST:event_jbkembaliActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_laporan_transaksi_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_laporan_transaksi_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_laporan_transaksi_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_laporan_transaksi_status.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_laporan_transaksi_status().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    public javax.swing.JButton jbcetak;
    public javax.swing.JButton jbkembali;
    public javax.swing.JComboBox<String> jcstatus;
    // End of variables declaration//GEN-END:variables
}
